### PR TITLE
Further commits to improve 409 duplicate token problems

### PR DESCRIPTION
**Pull request by kaminoo**
It seems to me pointless to keep retrying polling if the user decided to stop. This is generating a ton of problems on my side, and stopping the infinite polling when unneeded seems to work (will continue to test on production thru the day).

Also, I took your new option for timeout and added it to getUpdates.

### CODE REVIEW

**Comment by kaminoo** [comment]
Unfortunately this fix had little impact on the 409 problems :( they remain and crippling my server heavily, will continue to look and update the pull request when I find further problems

**Comment by kaminoo** [comment]
I think the issue is deep down the latest code you've added. I don't know the reasons for many of the things you did, but I can stop the 409 error. I had to revert to 0.1.4 that manages the polling differently. Will take a look from there on to see how to help you. I may have an idea, and it's related to my own code... but I think the bot isn't shutting down properly, and keeping the poll loop even after we've stopped it. Just a guess, will take a look.

**Comment by kaminoo** [comment]
Just sent the final pull request. Take a look. This finally fixed all my problems. Will continue to test on production on multiple bots.

**Comment by shernshiou** [comment]
@kaminoo I am checking. Thanks for the pull request. Please add your name to contributors if possible.

**Comment by kaminoo** [comment]
@shernshiou thank you for checking this out, hope you like the fixes, it's been more than 24hs and had 0 problems with the library. Fixing the 409 error was tough, but was actually based on your previous code. 0.1.4 was working fine, so I checked what changed and kind of reverted that with the new additions.

Once you feel this is ok I'll probably ask you if it would be possible to beautify the Bot.js code a little, and have 4-spaces tabs. It'll probably be a big commit since it will change everything, but I'll happily do it, since I plan to keep working on this library in the future. Just a suggestion, let me know how you feel.

**Comment by shernshiou** [comment]
@kaminoo yup thats the plan. Going to do some abstraction soon.

**Pull request merged**
