### PR TITLE
Fix for reject returned on succesful send Photo

### PR DESCRIPTION
**Pull request by SyRenity**
Otherwise the sending throws rejects

### CODE REVIEW

**Comment by shernshiou** [comment]
How did you get the textual result? I did not encounter this

**Comment by SyRenity** [comment]
@shernshiou exactly via the sendPhoto example (with filename only):
https://github.com/depoio/node-telegram-bot

**Comment by fisch0920** [comment]
@SyRenity #40 includes a slightly more robust version of this fix.  @shernshiou this is definitely a bug; see #40 for details.

**Comment by shernshiou** [comment]
@SyRenity thanks I will use your pull request instead.

**Pull request closed without merging**
