### PR TITLE
Enhancement/webhook

### PR DESCRIPTION
**Pull request by MrHug**
I have added an option to support the use of webhooks, rather than the polling based method. I made this some time ago, so had to rebase to the new master (like all the new features by the way :D)

If you already have a different way to support this, or you disagree with something, please let me know.

### CODE REVIEW

**Comment by fivepointseven** [comment]
Any examples on using webhook?

**Comment by MrHug** [comment]
You mean example code?

  logger.info("Setting up Telegram bot");
  var Bot = require('node-telegram-bot');

  var bot = new Bot({
    token: 'XXXXX',
    webhook: 'https://url:8443/telegram'
  }).start();


Now telegram will send POST requests to the specified URL with the messages.

**Comment by fivepointseven** [comment]
Thanks. It would be nice to put this in examples folder just in case ;)

**Comment by MrHug** [comment]
Sure thing :)

**Comment by MrHug** [comment]
Added example in c287a4fd4c5eae504e663c7d3101b836fde120c3

**Pull request merged**
