### PR TITLE
Added multiple arguments handling, fixed crash on service messages

### PR DESCRIPTION
**Pull request by fivepointseven**
Bot was crashing when i.e. added to the group because of split() error with that service message. This is fixed.
Also bot now returns any number of arguments for command as an array.

### CODE REVIEW

**Comment by shernshiou** [comment]
Can you remove your bot token?

**Comment by fivepointseven** [comment]
I did in the second commit

**Comment by Liryna** [comment]
I think he mean to rebase all your commits for removing your token from the git history.

**Comment by shernshiou** [comment]
:+1: @Liryna 
Yup I meant that.

**Comment by fivepointseven** [comment]
Ok, I have no idea what you guys are talking about. >_<
How do I do that?

**Comment by Liryna** [comment]
https://stackoverflow.com/questions/2563632/how-can-i-merge-two-commits-into-one

**Comment by fivepointseven** [comment]
I did something, not sure if it was the right thing. I'm a total noob with all these branches and pull request thingies >_<

**Comment by shernshiou** [comment]
I will take a look later.. Thanks for the commit!

**Pull request merged**
